import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import Heatmap from '../components/Heatmap';
import sampleAnalysis from '../data/sampleAnalysis.json';
import { TargetIcon, HashIcon, FlameIcon, ChartIcon } from '../components/icons';
import './LandingPage.css';

const FEATURES = [
  {
    id: 'tracking',
    icon: TargetIcon,
    title: 'Player Tracking',
    summary: 'YOLOv8 + TrackTrack detection',
    body: 'Every player on the pitch is detected frame-by-frame and followed across the match using motion-aware multi-object tracking, so you get a continuous movement trail per player instead of disconnected snapshots.',
  },
  {
    id: 'jersey',
    icon: HashIcon,
    title: 'Jersey Recognition',
    summary: 'OCR + manual verification',
    body: "Jersey numbers are read automatically wherever the camera angle allows it. For the tracks OCR can't confidently read, a reviewer can confirm identities by eye in the Verify Players screen. Real footage rarely gives you a perfect automatic result, so the fallback is built in rather than hiding the gap.",
  },
  {
    id: 'heatmap',
    icon: FlameIcon,
    title: 'Heatmaps',
    summary: 'Positional density over time',
    body: 'Every tracked position is aggregated into a pitch grid, showing you at a glance where a player, or the whole team, spent the match.',
  },
  {
    id: 'stats',
    icon: ChartIcon,
    title: 'Performance Stats',
    summary: 'Distance, speed, sprints',
    body: 'Distance covered, average speed, and sprint counts are computed per player directly from tracked movement, with jitter-smoothing so a shaky camera or a missed frame does not fake a sprint.',
  },
];

const STEPS = [
  {
    title: 'Add a match video',
    body: 'Upload a file (MP4, AVI, MOV, MKV, or FLV) or paste a link from YouTube, Instagram, TikTok, Facebook, X/Twitter, or Vimeo, then tag the teams and players involved.',
  },
  {
    title: 'Let it analyze',
    body: 'The video is queued and analyzed in the background: player detection, tracking, ball tracking, and jersey OCR all run automatically.',
  },
  {
    title: 'Review & verify',
    body: 'Check the report, fix any player identities the OCR could not read confidently, and merge tracks that split the same player in two.',
  },
  {
    title: 'Explore the data',
    body: 'Dig into heatmaps, per-player stats, and detected actions, all tied back to your team roster.',
  },
];

// sampleAnalysis.json is generated by server/scripts/seedDemoData.js from
// real anonymized match-tracking data (github.com/metrica-sports/sample-data).
// Every number here is computed the same way a real analysis run computes
// it (see that script), not hand-typed placeholder data.
const sampleActionCounts = sampleAnalysis.actions.reduce((counts, a) => {
  counts[a.type] = (counts[a.type] || 0) + 1;
  return counts;
}, {});
const sampleTopPlayers = [...sampleAnalysis.playerData]
  .sort((a, b) => b.statistics.distanceCovered - a.statistics.distanceCovered)
  .slice(0, 6);

const LandingPage = () => {
  const [activeFeature, setActiveFeature] = useState(FEATURES[0].id);
  const [openStep, setOpenStep] = useState(0);

  const feature = FEATURES.find((f) => f.id === activeFeature);

  return (
    <div className="landing">
      <section className="landing-hero">
        <div className="landing-hero-inner">
          <h1>Turn match footage into scouting data</h1>
          <p>
            Upload highlights, or import them from YouTube or social media, and get automatic player
            tracking, jersey identification, heatmaps, and performance stats. Includes a
            human-in-the-loop review step for the parts computer vision can't guess perfectly.
          </p>
          <div className="landing-hero-actions">
            <Link to="/register" className="landing-cta-primary">
              Get started free
            </Link>
            <Link to="/login" className="landing-cta-secondary">
              Sign in
            </Link>
          </div>
        </div>
      </section>

      <section className="landing-section">
        <h2>What you get</h2>
        <p className="landing-section-sub">Click a feature to see what it does.</p>
        <div className="landing-features">
          <div className="landing-feature-tabs">
            {FEATURES.map((f) => (
              <button
                key={f.id}
                className={`landing-feature-tab ${activeFeature === f.id ? 'active' : ''}`}
                onClick={() => setActiveFeature(f.id)}
              >
                <span className="landing-feature-icon">
                  <f.icon size={22} />
                </span>
                <span>
                  <strong>{f.title}</strong>
                  <span className="landing-feature-summary">{f.summary}</span>
                </span>
              </button>
            ))}
          </div>
          <div className="landing-feature-detail">
            <span className="landing-feature-detail-icon">
              <feature.icon size={32} />
            </span>
            <h3>{feature.title}</h3>
            <p>{feature.body}</p>
          </div>
        </div>
      </section>

      <section className="landing-section landing-section-alt">
        <h2>How it works</h2>
        <div className="landing-steps">
          {STEPS.map((step, index) => (
            <div key={step.title} className="landing-step">
              <button
                className="landing-step-header"
                onClick={() => setOpenStep(openStep === index ? -1 : index)}
                aria-expanded={openStep === index}
              >
                <span className="landing-step-number">{index + 1}</span>
                <span className="landing-step-title">{step.title}</span>
                <span className="landing-step-chevron">{openStep === index ? '−' : '+'}</span>
              </button>
              {openStep === index && <p className="landing-step-body">{step.body}</p>}
            </div>
          ))}
        </div>
      </section>

      <section className="landing-section">
        <h2>Sample report</h2>
        <p className="landing-section-sub">
          Real match data, run through the exact same analysis pipeline. Sign in to analyze your
          own footage.
        </p>
        <div className="landing-sample-card">
          <div className="landing-sample-header">
            <span>{sampleAnalysis.video.originalName}</span>
            <span className="landing-sample-badge">sample data</span>
          </div>
          <p className="landing-sample-meta">
            {sampleAnalysis.summary.totalPlayers} players tracked ·{' '}
            {Math.round(sampleAnalysis.summary.matchDuration / 60)} min of play ·{' '}
            {sampleAnalysis.actions.length} actions detected
          </p>

          <div className="landing-sample-actions">
            {Object.entries(sampleActionCounts).map(([type, count]) => (
              <span key={type} className={`landing-action-badge landing-action-badge-${type}`}>
                {count} {type}
                {count === 1 ? '' : 's'}
              </span>
            ))}
          </div>

          <div className="landing-sample-grid">
            <div className="landing-sample-heatmap">
              <h4>Heatmap</h4>
              <Heatmap grid={sampleAnalysis.heatmapData.grid} sport={sampleAnalysis.video.sport} />
            </div>

            <div className="landing-sample-table-wrap">
              <h4>Top players by distance covered</h4>
              <table className="landing-sample-table">
                <thead>
                  <tr>
                    <th>Player</th>
                    <th>Kit</th>
                    <th>Distance</th>
                    <th>Avg. speed</th>
                    <th>Sprints</th>
                  </tr>
                </thead>
                <tbody>
                  {sampleTopPlayers.map((p) => (
                    <tr key={p.trackId}>
                      <td>{p.playerName}</td>
                      <td>{p.teamColor}</td>
                      <td>{p.statistics.distanceCovered} m</td>
                      <td>{p.statistics.averageSpeed} m/s</td>
                      <td>{p.statistics.sprintCount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <p className="landing-sample-attribution">
            Source: real anonymized match tracking data from{' '}
            <a href="https://github.com/metrica-sports/sample-data" target="_blank" rel="noreferrer">
              Metrica Sports' public sample-data repository
            </a>
            .
          </p>
        </div>
      </section>

      <section className="landing-cta-band">
        <h2>Ready to analyze your own match footage?</h2>
        <Link to="/register" className="landing-cta-primary">
          Create a free account
        </Link>
      </section>
    </div>
  );
};

export default LandingPage;
